development: # development
  type: "postgres"
  host: "localhost"
  port: 5432
  username: "type-graphql-user"
  password: "password"
  database: "type_graphql_db"
  synchronize: true
  logging: true
  entities: ["src/entity/*.*"]
  cli:
    entitiesDir: "src/entity"
    migrationsDir: "src/migration"
    subscribersDir: "src/subscriber"

test: # test
  type: "postgres"
  host: "localhost"
  port: 5432
  username: "type-graphql-user"
  password: "password"
  database: "type_graphql_db_test"
  synchronize: true
  dropSchema: true
  entities: ["src/entity/*.*"]

production: # production
  type: "postgres"
  host: "localhost"
  port: 5432
  username: "type-graphql-user"
  password: "password"
  database: "type_graphql_db"
  synchronize: true
  logging: true
  entities: ["dist/src/entity/*.*"]
