default: # default connection
  type: "postgres"
  host: "localhost"
  port: 5432
  username: "type-graphql-user"
  password: "password"
  database: "type_graphql_db"
  synchronize: true
  logging: true
  entities: ["src/entity/*.*"]
